---
- name: Windows updates
  hosts: windows_group
  vars:
    report_server: 10.0.0.8

  tasks:
    - name: Patch windows server
      ansible.builtin.include_role:
        name: demo.patching.patch_windows

    - name: Build report server
      delegate_to: "{{ report_server }}"
      run_once: true  # noqa: run-once[task]
      block:
        - name: Install report server
          ansible.builtin.include_role:
            name: "{{ item }}"
          loop:
            - demo.patching.report_server
            - demo.patching.report_windows
            - demo.patching.report_windows_patching

        - name: Update landing page
          ansible.builtin.include_role:
            name: demo.patching.report_server
            tasks_from: windows_landing_page
